Repository so-mouga/memoriz-front, pull requests merged in 2019-03, with the labels that each got.

#7 chore(infrastructure): edit MakeFile
  Makefile
Labels: bug

#10 feat(front): Add style page login
  src/app/auth/log-in/log-in.page.html
  src/app/auth/log-in/log-in.page.scss
  src/app/auth/log-in/log-in.page.ts
  src/assets/img/logo-1.png
  src/assets/scss/global-styles.scss
  src/environments/environment.ts
  src/global.scss
Labels: front

#12 feat(back): Add config prettier
  .prettierignore
  .prettierrc.json
  Makefile
  package-lock.json
  package.json
  tslint.json
Labels: back
